steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fastapi-app', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fastapi-app']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'fastapi-service'
    - '--image'
    - 'gcr.io/$PROJECT_ID/fastapi-app'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'CLOUD_PROVIDER=google-cloud'
    - '--memory'
    - '512Mi'
    - '--cpu'
    - '1'

images:
  - 'gcr.io/$PROJECT_ID/fastapi-app'
